Unity upgrade to 9.x.x
moengage/MoEngage-Unity-SDK pull request #12
Opened 2023-07-10 12:15 UTC by RakshithaAcharya

https://moengagetrial.atlassian.net/browse/MOEN-25155
Unity upgrade to 9.x.x

2023-07-13 04:54 UTC, umangmoe requested changes

2023-07-13 04:54 UTC, umangmoe commented on Core-SDK/Assets/MoEngage/Scripts/Model/InAppCampaignContext.cs
> +    public InAppCampaignContext(Dictionary < string, object > campaignContextPayload) {
Move out the parsing logic to the parser class.

2023-07-13 04:54 UTC, umangmoe commented on Core-SDK/Assets/MoEngage/Scripts/Model/SelfHandled.cs
> +    public SelfHandled(Dictionary < string, object > selfHandledDictionary) {
move the parsing to parser class.

2023-07-13 04:54 UTC, umangmoe commented on iOS/MoEngageConfiguration.h
> +#define kMoEngageRegion @"DATA_CENTER_01" // DATA_CENTER_01/DATA_CENTER_02/DATA_CENTER_03/DATA_CENTER_04/DATA_CENTER_05
Let's not set a default data center if possible

2023-07-20 10:57 UTC, umangmoe requested changes
- Add comments for all public models
- Properties object should not be in models, move it out.

2023-07-20 10:57 UTC, umangmoe commented on Core-SDK/Assets/MoEngage/Scripts/MoEngageUnityPlatform.cs
> +  public interface MoEngageUnityPlatform {
add documentation

2023-07-20 10:57 UTC, umangmoe commented on Core-SDK/Assets/MoEngage/Scripts/Utils/MoEUtils.cs
> +
All methods where we are converting string --> model or json --> model can be moved to a parser class

2023-07-25 09:13 UTC, RakshithaAcharya commented on Core-SDK/Assets/MoEngage/Scripts/Model/InAppCampaignContext.cs
> +    public InAppCampaignContext(Dictionary < string, object > campaignContextPayload) {
@umangmoe done

2023-07-25 09:13 UTC, RakshithaAcharya commented on Core-SDK/Assets/MoEngage/Scripts/Model/SelfHandled.cs
> +    public SelfHandled(Dictionary < string, object > selfHandledDictionary) {
@umangmoe done

2023-07-25 09:13 UTC, RakshithaAcharya commented on iOS/MoEngageConfiguration.h
> +#define kMoEngageRegion @"DATA_CENTER_01" // DATA_CENTER_01/DATA_CENTER_02/DATA_CENTER_03/DATA_CENTER_04/DATA_CENTER_05
@umangmoe done

2023-07-25 09:13 UTC, RakshithaAcharya commented on Core-SDK/Assets/MoEngage/Scripts/MoEngageUnityPlatform.cs
> +  public interface MoEngageUnityPlatform {
@umangmoe done

2023-07-25 09:13 UTC, RakshithaAcharya commented on Core-SDK/Assets/MoEngage/Scripts/Utils/MoEUtils.cs
> +
@umangmoe done

2023-07-25 09:26 UTC, merged