Version export iOS
moengage/MoEngage-Unity-SDK pull request #24
Opened 2024-04-17 11:58 UTC by RakshithaAcharya

2024-04-22 09:15 UTC, arshiya-moengage commented
Please add the description and jira link in the description section

2024-04-22 11:00 UTC, arshiya-moengage commented on Core-SDK/Assets/MoEngage/Editor/PostProcessBuild_iOS.cs
> +        using (StreamWriter sw = File.AppendText(path + "/Libraries/MoEngage/Plugins/iOS/MoEUnityConstants.m"))
Why cant we pass the version in the `Initialize()` payload instead?

2024-04-23 04:43 UTC, RakshithaAcharya commented on Core-SDK/Assets/MoEngage/Editor/PostProcessBuild_iOS.cs
> +        using (StreamWriter sw = File.AppendText(path + "/Libraries/MoEngage/Plugins/iOS/MoEUnityConstants.m"))
@arshiya-moengage Before `initialise` method is called, sdk will already be initialised from native iOS side.

2024-04-24 06:10 UTC, umangmoe requested changes
This PR should only have version tracking change and not SDK version upgrade. Please raise a separate PR for SDK version upgrade.

2024-04-25 02:56 UTC, umangmoe approved these changes

2024-04-25 06:10 UTC, merged